apiVersion: 1

datasources:
  - name: ClickHouse
    uid: PDEE91DDB90597936
    type: grafana-clickhouse-datasource
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      username: default
      defaultDatabase: sensors
      protocol: http
    secureJsonData:
      password: sensorhouse
